export default {
  CHECK_AUTH_STATUS: 'CHECK_AUTH_STATUS',
  CHECK_AUTH_STATUS_FAIL: 'CHECK_AUTH_STATUS_FAIL',
  CHANGE_REPORT_STATUS: 'CHANGE_REPORT_STATUS',
  GET_USER_REPORTS: 'GET_USER_REPORTS',
  LOG_IN: 'LOG_IN',
  LOGOUT: 'LOGOUT',
  MAKE_NEW_REPORT: 'CREATE_REPORT',
  SIGN_UP: 'SIGN_UP',
  START_FETCHING: 'START_FETCHING',
  STOP_FETCHING: 'STOP_FETCHING',

};
